### ISSUE TITLE
GIT: Unable to access repository

### ISSUE THREAD

**Issue by kurdibogdan** [vgyorgy/craftmanship_training#2]
I was unable to download the source codes from home office (possibily the GIT isn't configured properly). The error log:
> **git clone http://github.com/vgyorgy/craftmanship_training.git**
> Cloning into 'craftmanship_training'...
> fatal: unable to access 'https://github.com/vgyorgy/craftmanship_training.git/': Received HTTP code 403 from proxy after CONNECT

Workaround: Download the source codes from web, unpack in VMware Linux.

**Comment by gonczi** [comment]
_Workaround: Download the source codes from web, unpack in VMware Linux._
Then how would you like to push back?

Please, read this or similar:
https://gist.github.com/evantoli/f8c23a37eb3558ab8765

**Comment by vgyorgy** [comment]
Please check your .git/config file. It should contain following section:
[remote "origin"]
	url = ssh://git@github.com/vgyorgy/craftmanship_training.git
	fetch = +refs/heads/*:refs/remotes/origin/*    

As github documentation, do not use user/password credentials here. The user is always git for SSH instead of your name.

**Comment by kurdibogdan** [comment]
Can you tell me the proxyUsername, proxyPassword, proxy.server.com, and port?
There isn't any .git folder, because it is created after cloning (and the problem is that git clone doesn't work).

**Comment by kurdibogdan** [comment]
Solved.
No proxy needed with VPN connection:
- git config --global --unset http.proxy

Proxy needed from office:
- git config --global http.proxy http://[ip]:[port]
IP and port is described in OneNote / "Proxy beállítása SVN-hez, GIT-hez"

**Comment by kurdibogdan** [comment]
Solution: use BBRAUN_guest network.
