### ISSUE TITLE
CMake can't find build directory.

### ISSUE THREAD

**Issue by kurdibogdan** [vgyorgy/craftmanship_training#3]
Error log:
> **deveushu@atd-vm-xp64:~/workspace/craftmanship_training-main$ cmake -B ./build**
> CMake Error: The source directory "/home/deveushu/workspace/craftmanship_training-main/build" does not appear to contain 
> CMakeLists.txt.
> Specify --help for usage, or press the help button on the CMake GUI.

**Comment by kurdibogdan** [comment]
Solution: cmake requires a folder as input that contains CMakeLists.txt. The folder is the project root, so we need to navigate back in folder structure, and run **cmake -B ./craftmanship_training-main/**

**Comment by gonczi** [comment]
"_Solution: cmake requires a folder as input that contains CMakeLists.txt. The folder is the project root, so we need to navigate back in folder structure, and run cmake -B ./craftmanship_training-main/_"

DO NOT!  - Run **cmake -B ./build** where is the  CMakeLists.txt.  CMakeLists.txt is the cmake input, and the ./build is the output.

**Comment by kurdibogdan** [comment]
Doesn't work. Do I need to manually create the "build" directory? If I run the cmake command from the project root (there is CMakeLists.txt), then I get the error message above.

**Comment by kurdibogdan** [comment]
OK. The problem was that I used cmake version 3.7.2 that has another syntax. The readme shall define the correct version.
> **sudo apt-get install libssl-dev**  # install OpenSSL development package
> **sudo apt remove --purge --auto-remove cmake**    # If you have already installed CMake using Ubuntu package manager, use the command below to remove it.
> **wget https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0.tar.gz** # download cmake package
> **tar -zxvf cmake-3.22.0.tar.gz**  # unzip
> **cd cmake-3.22.0**
> **./bootstrap**    # compile and install CMake
> **make**
> **sudo make install**
> **cmake --version**   #  verify installation and check the correctness of the installed version

**Comment by kurdibogdan** [comment]
After bootstrap and make succeed, the "sudo make install" command crashed :(
>**sudo make install**
>Consolidate compiler generated dependencies of target cmsys
>Source/kwsys/CMakeFiles/cmsys.dir/compiler_depend.make:4: *** missing separator. Stop.
>CMakeFiles/Makefile2:1488: recipe for target 'Source/kwsys/CMakeFiles/cmsys.dir/all' failed
>make[1]: *** [Source/kwsys/CMakeFiles/cmsys.dir/all] Error 2
>Makefile:165: recipe for target 'all' failed
>make: *** [all] Error 2

**Comment by kurdibogdan** [comment]
Cmake 3.21.0 works. Install steps: https://trendoceans.com/how-to-install-cmake-on-debian-10-11/
* sudo apt install build-essential gcc libssl-dev
* wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0.tar.gz
* tar xvf cmake-3.21.0.tar.gz
* cd cmake-3.21.0
* ./bootstrap 
* **make**
* sudo make install
* cmake --version
