### ISSUE TITLE
CMake can't find GoogleTest file and "gtest_discover_tests" command

### ISSUE THREAD

**Issue by kurdibogdan** [vgyorgy/craftmanship_training#5]
Error log:
> **deveushu@atd-vm-xp64:~/workspace/craftmanship_training-main$ cmake -B ./**
> -- The C compiler identification is GNU 6.3.0
> -- The CXX compiler identification is GNU 6.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found GTest: /usr/local/lib/libgtest.a  
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> CMake Error at CMakeLists.txt:19 (include):
>   include could not find load file:
> 
>     GoogleTest
> 
> 
> CMake Error at CMakeLists.txt:20 (gtest_discover_tests):
>   Unknown CMake command "gtest_discover_tests".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/deveushu/workspace/craftmanship_training-main/CMakeFiles/[CMakeOutput.log](https://github.com/vgyorgy/craftmanship_training/files/7656924/CMakeOutput.log)".
> See also "/home/deveushu/workspace/craftmanship_training-main/CMakeFiles/[CMakeError.log](https://github.com/vgyorgy/craftmanship_training/files/7656923/CMakeError.log)".

**Comment by gonczi** [comment]
You should wipe out the whole of your project  (delete and clone again)! 
Then: _cmake -B ./**build**_
DO NOT build into the root because it will not work.

**Comment by vgyorgy** [comment]
It is already written in readme file.

**Comment by kurdibogdan** [comment]
Same as #3

**Comment by kurdibogdan** [comment]
Use CMake 3.21.0.
