### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by kurdibogdan** [vgyorgy/craftmanship_training#6]
Error log:
> **cmake --build ./ --config Debug --target craftmanship_training_test -j 14**
> Unknown argument -j
> Unknown argument 14
> Usage: cmake --build <dir> [options] [-- [native-options]]
> Options:
>   <dir>          = Project binary directory to be built.
>   --target <tgt> = Build <tgt> instead of default targets.
>                    May only be specified once.
>   --config <cfg> = For multi-configuration tools, choose <cfg>.
>   --clean-first  = Build target 'clean' first, then build.
>                    (To clean only, use --target 'clean'.)
>   --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
>   --             = Pass remaining options to the native tool.

**Comment by gonczi** [comment]
Same as #5

**Comment by kurdibogdan** [comment]
Same as #3

**Comment by kurdibogdan** [comment]
Use CMake 3.21.0.
